import { NextRequest, NextResponse } from "next/server";
import { readManifest } from "@/lib/features/registry";
import { buildHandoff } from "@/lib/handoff/handoff";
import { readTargetFile } from "@/lib/handoff/resolve";
import { getChoices } from "@/lib/handoff/store";
import { integrateHtml, newFileContent, unifiedPatch } from "@/lib/handoff/integrate";

/** Combined git apply-able patch for the whole feature. */
export async function GET(_req: NextRequest, { params }: { params: Promise<{ key: string }> }) {
  const { key } = await params;
  const manifest = await readManifest(key);
  if (!manifest) return new NextResponse("Not found", { status: 404 });

  const pkg = await buildHandoff(manifest);
  const choices = await getChoices(key);
  const parts: string[] = [
    `# Handoff patch — ${manifest.name} (${key})`,
    `# Generated by OUTRIGGER Prototype Console. Review before applying.`,
    `# ${pkg.summary}`,
    ``,
  ];

  for (const p of pkg.pieces) {
    if (p.kind === "html") {
      const chosen = (p.selector && choices.targets[p.selector]) || p.targetFile;
      const original = chosen ? await readTargetFile(chosen) : null;
      if (original != null && chosen) {
        const { integrated } = integrateHtml(original, p.code, key, p.anchorTokens ?? []);
        parts.push(unifiedPatch(chosen, original, integrated));
      } else {
        parts.push(`# HTML: no resolved target — dev must choose the owning view.\n# Markup:\n${p.code.split("\n").map((l) => "# " + l).join("\n")}\n`);
      }
    } else {
      const path = p.kind === "css"
        ? `OUT.Website/wwwroot/assets/scss/blocks/_${key}.scss`
        : `OUT.Website/Features/Outrigger/Blocks/${key}.ts`;
      const content = newFileContent(`// ${manifest.name} — from prototype ${key}`, p.code);
      parts.push(unifiedPatch(path, "", content));
    }
  }

  return new NextResponse(parts.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${key}.patch"`,
    },
  });
}
