/**
 * OWNERSHIP AND ATTRIBUTION — one place, so a rename or a change of counsel's
 * wording is a single edit rather than a hunt through every surface that
 * prints, exports or ships something.
 *
 * Every artifact this platform produces carries the notice: the readout PDF on
 * EVERY page, the stamped verdict record, the integration package, and any HTML
 * export. A visible watermark can be cropped out of a screenshot, so each
 * artifact also carries a traceability line naming the org, the experiment and
 * the moment it was generated — that is the part that does work if ownership is
 * ever actually contested.
 */

/** The product has no public name yet, so nothing asserts one — the notice
 *  states ownership, which is the part that matters. Set NAME and it appears
 *  everywhere the notice does, without touching another file. */
export const PRODUCT_NAME: string | null = null;
export const OWNER = "INHQ Inc.";
export const OWNER_LEGAL = "INHQ Inc.";

/** The year the notice asserts. Rolls forward on its own. */
export const noticeYear = () => new Date().getFullYear();

/** One line, for footers and headers where space is short. */
export function shortNotice(): string {
  return `${PRODUCT_NAME ? `${PRODUCT_NAME} · ` : ""}A product of ${OWNER} · © ${noticeYear()} ${OWNER} All rights reserved. · Confidential and proprietary`;
}

/** The full assertion. Reviewed wording goes HERE and nowhere else. */
export function fullNotice(): string {
  return [
    `© ${noticeYear()} ${OWNER_LEGAL} All rights reserved.`,
    `This platform, including without limitation its source code, interfaces,`,
    `data models, analytical methods, and all outputs generated by it — readouts, verdict`,
    `records, measurement plans, integration packages, exports and derivative reports`,
    `(collectively, the "Materials") — is the exclusive property of ${OWNER_LEGAL} and is`,
    `confidential and proprietary. No part may be reproduced, distributed, or used to create`,
    `derivative works without the express written permission of ${OWNER_LEGAL}`,
  ].join(" ");
}

/**
 * The traceability stamp. Names WHAT was generated, for WHOM, and WHEN — so a
 * document separated from its context can still be placed. `at` is passed in
 * rather than read from the clock: a stamped record must print the same line
 * every time it is printed, or the "immutable record" is not one.
 */
export function provenanceLine(opts: {
  org?: string | null;
  experiment?: string | null;
  recordId?: string | null;
  at?: string | null;
}): string {
  const parts = [
    PRODUCT_NAME ? `Generated by ${PRODUCT_NAME}` : "Generated by",
    OWNER,
    opts.org?.trim() || null,
    opts.experiment?.trim() || null,
    opts.at ? new Date(opts.at).toISOString().replace(".000", "") : new Date().toISOString().replace(/\.\d{3}/, ""),
    opts.recordId?.trim() || null,
  ].filter(Boolean);
  return parts.join(" · ");
}
