/* GENERATED by scripts/build-home-page-v2.sh — do not edit.
   Sources: prototypes/home-page-v2/variation.js + prototypes/explorer-nav/variation.js
   Combined for ONE preview URL. They remain separate A/B tests. */

/**
 * Outrigger home page — test 01 + 03 variation
 *
 *  1. The Travel Quiz promo card from /test/tqpromos, run full-bleed, directly under the
 *     destination explorer. Same artwork, eyebrow, headline and CTA as the component there.
 *  2. Property tiles: "Book Now" -> "View Availability" (keeps the widget and every data-bw-* attr);
 *     "Learn More" -> "View Rooms", pointing at that property's /rooms-suites page.
 *  3. Offer tiles: the CTA stops linking out to reservation.outrigger.com and instead opens the
 *     on-site widget, carrying the promo across as data-bw-offer-code / data-bw-offer-code-type
 *     and the stay length as data-bw-length-of-stay — the same attribute contract the
 *     /offers/campaign/2026/bc/ohr page already uses on its "Search availability" button.
 *
 * Idempotent, and re-applies on DOM churn (the offers/property rails are Swiper, which clones slides).
 */
(function () {
  'use strict';

  var ARROW = function (stroke) {
    return '<span class="icon-arrow" style="display:flex;margin-left:4px">' +
      '<svg width="12" height="16" viewBox="0 0 12 16" fill="none" xmlns="http://www.w3.org/2000/svg">' +
      '<path d="m4.5,3.49174l4,4l-4,4" stroke="' + stroke + '" stroke-width="2"></path></svg></span>';
  };

  /* ---------------------------------------------------------------- 1. banner
   * The Travel Quiz promo card from /test/tqpromos, run full-bleed under the
   * destination explorer. Type tokens (DuplicateIonic-Black eyebrow at 4px
   * tracking, DuplicateSans-Regular headline, Montserrat-Light body, outlined
   * white CTA) are lifted from that component's computed styles.
   *
   * The artwork only exists at 517x643 — the AdaptiveImages `stamp` signs the
   * width/height, so a larger render cannot be requested. It is therefore run
   * at native scale as a right-hand accent over a gradient drawn from its own
   * palette, rather than stretched across 1440px and turned to mush.
   */
  var PROMO_IMG = 'https://www.outrigger.com/AdaptiveImages/optimizely/' +
    '5771c854-7b02-49d2-8ab8-1ca80ec981a6/promo2.png' +
    '?quality=100&width=1400&height=1741&stamp=9b0851ecb0a4dc9b51c8688da56e73c05f2829ab&format=webp';

  function styles() {
    if (document.getElementById('opmc-tq-style')) return;
    var st = document.createElement('style');
    st.id = 'opmc-tq-style';
    st.textContent = [
      '#opmc-tq-banner{position:relative;width:100%;display:block;overflow:hidden;background:#0E2E42}',
      // ONE layer at cover. Compositing the art over a hand-made gradient left a hard
      // vertical seam where the two grounds met — letting the artwork be the ground
      // across the full width removes the boundary entirely.
      '#opmc-tq-banner .tq-bg{position:absolute;inset:0;background-image:url("' + PROMO_IMG + '");' +
        'background-size:cover;background-position:center 32%;background-repeat:no-repeat}',
      '#opmc-tq-banner .tq-scrim{position:absolute;inset:0;background:linear-gradient(90deg,' +
        'rgba(8,26,40,.9) 0%,rgba(8,26,40,.72) 34%,rgba(8,26,40,.35) 62%,rgba(8,26,40,.12) 100%)}',
      '#opmc-tq-banner .tq-inner{position:relative;max-width:1280px;margin:0 auto;padding:88px 36px;' +
        'display:flex;flex-direction:column;align-items:flex-start;min-height:440px;justify-content:center}',
      '#opmc-tq-banner .tq-eyebrow{font:900 14px/18px DuplicateIonic-Black,sans-serif;color:#fff;' +
        'letter-spacing:4px;text-transform:uppercase;margin:0 0 28px}',
      '#opmc-tq-banner .tq-title{font:clamp(34px,4.4vw,56px)/1.1 DuplicateSans-Regular,sans-serif;' +
        'color:#fff;margin:0 0 18px;max-width:16ch}',
      '#opmc-tq-banner .tq-text{font:325 16px/25px Montserrat-Light,sans-serif;color:#fff;margin:0 0 34px;max-width:50ch}',
      '#opmc-tq-banner .tq-cta{font:500 16px/16px DuplicateSans-Medium,sans-serif;color:#fff;background:transparent;' +
        'border:1px solid #fff;padding:16px;display:inline-flex;align-items:center;text-decoration:none;transition:.15s}',
      '#opmc-tq-banner .tq-cta:hover{background:#fff;color:#0B2233}',
      '#opmc-tq-banner .tq-cta:hover path{stroke:#0B2233}',
      // Top Offers onto the destination explorer's sand ground. `.is-sand` is the site's
      // own theme (it flips the type to dark); the explorer's exact warm tone is not any
      // theme class, so it is set explicitly so the two sections read as one surface.
      '.offers-slider.is-sand{background-color:rgb(241,239,237) !important}',
      '@media(max-width:767px){#opmc-tq-banner .tq-inner{padding:56px 20px;min-height:340px}' +
        '#opmc-tq-banner .tq-scrim{background:linear-gradient(180deg,rgba(8,26,40,.55) 0%,rgba(8,26,40,.9) 100%)}}'
    ].join('');
    document.head.appendChild(st);
  }

  function banner() {
    if (document.getElementById('opmc-tq-banner')) return true;
    var ds = document.querySelector('.destination-selection');
    if (!ds) return false;

    var el = document.createElement('div');
    el.id = 'opmc-tq-banner';
    el.setAttribute('data-tag-item', 'travel_quiz_banner');
    el.innerHTML =
      '<div class="tq-bg" aria-hidden="true"></div>' +
      '<div class="tq-scrim" aria-hidden="true"></div>' +
      '<div class="tq-inner">' +
        '<div class="tq-eyebrow">Outrigger Travel Quiz</div>' +
        '<div class="tq-title">Let’s discover your perfect getaway</div>' +
        '<div class="tq-text">What’s your vibe when you’re seeking an escape to paradise? Answer these quick questions and we’ll suggest a destination to fit your travel dreams.</div>' +
        '<a href="/travel-quiz" class="tq-cta" data-tag-item="travel_quiz_banner_cta">Take the quiz' + ARROW('white') + '</a>' +
      '</div>';

    ds.insertAdjacentElement('afterend', el);
    return true;
  }

  /* ------------------------------------------------------ 2. property tiles */
  function tiles() {
    var n = 0;
    document.querySelectorAll('.card-cta-info').forEach(function (cta) {
      // `.card-cta-info` is NOT unique to the home page's property tiles — the
      // booking widget's own property picker renders the same markup inside
      // #bookingWidget. Relabelling those rewrites the booking flow itself, so
      // anything inside an offcanvas is off limits.
      if (cta.closest('#bookingWidget, .offcanvas')) return;
      var bn = cta.querySelector('.bw-magic-link');
      var lm = cta.querySelector('.card-view-property');
      if (!bn || !lm || cta.dataset.mockDone === '1') return;

      // Book Now -> View Availability. Widget behaviour and every data-bw-* attribute untouched.
      bn.innerHTML = 'View Availability' + ARROW('#332926');
      bn.setAttribute('data-tag-item', 'property_card_view_availability_cta');

      // Learn More -> View Rooms, pointed at the property's rooms & suites page.
      var prop = (lm.getAttribute('href') || '').replace(/\/+$/, '');
      if (prop && !/\/rooms-suites$/.test(prop)) lm.setAttribute('href', prop + '/rooms-suites');
      lm.textContent = 'View Rooms';
      lm.setAttribute('data-tag-item', 'property_card_view_rooms_cta');

      cta.dataset.mockDone = '1';
      n++;
    });
    return n;
  }

  /* --------------------------------------------------------- 3. offer tiles */
  function offers() {
    var n = 0;
    document.querySelectorAll('.offers-slider a[href*="reservation.outrigger.com"]').forEach(function (a) {
      var u;
      try { u = new URL(a.href); } catch (e) { return; }
      var promo  = u.searchParams.get('promo');
      var nights = u.searchParams.get('nights');

      var b = document.createElement('button');
      b.type = 'button';
      b.className = 'button bw-magic-link';
      b.setAttribute('data-bs-toggle', 'offcanvas');
      b.setAttribute('data-bs-target', '#bookingWidget');
      b.setAttribute('aria-controls', 'bookingWidget');
      b.setAttribute('data-button-origin', location.href);
      b.setAttribute('data-bw-chain', '18497');
      b.setAttribute('data-bw-prices-language', 'Prices shown in');
      b.setAttribute('data-bw-prices-language-subtext', 'Lowest daily rate (does not include taxes and fees)');
      if (promo) {
        b.setAttribute('data-bw-offer-code', promo);
        b.setAttribute('data-bw-offer-code-type', 'Promotion');
      }
      if (nights) b.setAttribute('data-bw-length-of-stay', nights);
      b.setAttribute('data-alt-cta-text', 'Search availability');
      b.setAttribute('data-tag-item', 'top_offers_widget_cta');
      b.innerHTML = 'Search availability' + ARROW('#332926');

      a.replaceWith(b);
      n++;
    });
    return n;
  }

  /* ------------------------------------------------- 4. Top Offers → sand */
  function offersTheme() {
    var o = document.querySelector('.offers-slider');
    if (!o || o.classList.contains('is-sand')) return;
    o.classList.remove('is-turquoise');
    o.classList.add('is-sand');
  }

  function apply() { styles(); banner(); tiles(); offers(); offersTheme(); }

  apply();
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', apply);
  new MutationObserver(apply).observe(document.documentElement, { childList: true, subtree: true });
  window.__outriggerHomeV2 = apply;
})();

/**
 * Outrigger home page — explorer navigation (step one of the Grid/Map explorer)
 *
 * No back arrow, no levels, no hidden state. Both tiers are on screen at once
 * and one thing in each is always selected:
 *
 *   Hawaii  Thailand  Fiji  Mauritius  Maldives     ← destination; selected one is the headline
 *   [Oahu 4] [Maui 2] [Hawaii Island 1] [Kauai 1]   ← regions of it; one always selected
 *
 * WHY NO BACK ARROW. A drill-down was tried and abandoned. On first load nobody
 * has navigated anywhere, so "←" answers a question the visitor never asked —
 * back to what? It also buried destination switching one click deeper, and that
 * is the fastest-growing action on the page (dropdown +12.7% vs tabs +8.3%).
 *
 * WHY NOTHING IS BEHIND A DISCLOSURE. Verndale's reviewer reported missing the
 * dropdown entirely — "I also missed the drop down at first" — while it was the
 * single biggest gainer in the experiment. Whatever replaces it has to be MORE
 * discoverable, not more elegant, so the whole set stays visible at rest.
 *
 * Type is the site's own: 60px/66px DuplicateSans-Regular for the selected
 * destination, 18px DuplicateSans-Medium for the others, 16px for the chips.
 * Navy (rgb(0,69,97)) is reserved for the selected state — a solid navy bar
 * fought the sand section, and a white bar read as a stray card inside it.
 *
 * Switching delegates to the site's own controls (the dropdown's .dropdown-item
 * and the region tab buttons), so this changes the affordance, not the behaviour.
 *
 * NOTE: render() owns every mutation inside the nav. Do NOT add a MutationObserver
 * that edits it — an earlier version did and hung the renderer.
 *
 * Runs ALONE: it alters the best-performing surface on the page.
 * Guardrail: explorer engagement (tabs + destination selection) must not fall.
 */
(function () {
  'use strict';

  var REGION_COUNTS = { 'Oahu': 4, 'Maui': 2, 'Hawaii Island (Big Island)': 1, 'Kauai': 1 };
  var STYLE_ID = 'opmc-nav-style', NAV_ID = 'opmc-nav', NAVY = 'rgb(0,69,97)', INK = 'rgb(51,41,38)';

  function styles() {
    if (document.getElementById(STYLE_ID)) return;
    var st = document.createElement('style');
    st.id = STYLE_ID;
    st.textContent = [
      '.destination-selection-dropdown{display:none !important}',
      '#destination-selection .col-md-4{display:none !important}',
      '#destination-selection .col-md-8{flex:0 0 100%;max-width:100%}',
      '.destination-selection-tabs-list{display:none !important}',   // site's own tabs — we drive them
      '.destination-selection-tabs{display:block !important}',        // wrapper is flex; without this the tiers sit side by side

      // tier 1 — destinations. Selected one keeps the site's 60px headline;
      // the rest sit on its baseline at the site's tab size.
      '#opmc-dests{display:flex;align-items:baseline;flex-wrap:wrap;gap:6px 20px;padding:0;margin:0 0 18px;list-style:none}',
      'h2.destination-selection-selected{display:none !important}',   // we render the name ourselves
      '#opmc-dests button{font:500 18px/18px DuplicateSans-Medium,sans-serif;color:rgba(51,41,38,.5);' +
        'background:none;border:0;padding:6px 0;cursor:pointer;white-space:nowrap;position:relative;' +
        'transition:color .15s}',
      '#opmc-dests button:hover{color:' + NAVY + '}',
      // the selected destination IS the headline — a class change, never a DOM move
      '#opmc-dests button.on{font:60px/66px DuplicateSans-Regular,sans-serif;color:rgb(33,37,41);' +
        'padding:0 0 6px;cursor:default}',
      '#opmc-dests button.on::after{content:"";position:absolute;left:0;right:0;bottom:0;height:3px;' +
        'background:' + NAVY + '}',
      '@media(max-width:767px){#opmc-dests button.on{font-size:38px;line-height:44px}}',
      '#opmc-dests button:focus-visible{outline:2px solid ' + NAVY + ';outline-offset:3px}',

      // tier 2 — regions of the selected destination
      '#' + NAV_ID + '{display:block;width:100%;margin:0 0 6px}',
      '#opmc-regions{display:flex;flex-wrap:wrap;gap:8px;padding:0;margin:0;list-style:none;align-items:center}',
      '#opmc-regions button{font:500 16px/16px DuplicateSans-Medium,sans-serif;color:' + INK + ';' +
        'background:transparent;border:1px solid rgba(51,41,38,.28);border-radius:7px;padding:11px 16px;' +
        'cursor:pointer;transition:.15s;white-space:nowrap;display:inline-flex;align-items:center;gap:7px}',
      '#opmc-regions button:hover{border-color:' + NAVY + ';color:' + NAVY + '}',
      '#opmc-regions button.on{background:' + NAVY + ';color:#fff;border-color:' + NAVY + '}',
      '#opmc-regions button:focus-visible{outline:2px solid ' + NAVY + ';outline-offset:2px}',
      '#opmc-regions button i{font-style:normal;font-size:14px;opacity:.5;font-weight:500}',
      '#opmc-regions button:hover i,#opmc-regions button.on i{opacity:.75}',
      '#opmc-note{font:16px/25px Montserrat-Light,sans-serif;color:rgba(51,41,38,.6)}',

      '@media(max-width:767px){#opmc-dests{gap:4px 16px;margin-bottom:14px}' +
        '#opmc-dests button{font-size:16px}' +
        '#opmc-regions button{font-size:15px;padding:10px 14px}}'
    ].join('');
    document.head.appendChild(st);
  }

  function destItems()  { return [].slice.call(document.querySelectorAll('.destination-selection-dropdown .dropdown-item')); }
  function regionBtns() { return [].slice.call(document.querySelectorAll('.destination-selection-tabs-lists button')); }
  function label(el)    { return (el.innerText || '').replace(/\s+/g, ' ').trim(); }

  function build() {
    var h2 = document.querySelector('h2.destination-selection-selected');
    if (!h2 || !destItems().length) return null;
    if (document.getElementById(NAV_ID)) return document.getElementById(NAV_ID).__ctl;

    styles();

    var dests = document.createElement('ul'); dests.id = 'opmc-dests';
    dests.setAttribute('aria-label', 'Destination');
    var nav   = document.createElement('div'); nav.id = NAV_ID;
    var regs  = document.createElement('ul'); regs.id = 'opmc-regions';
    regs.setAttribute('aria-label', 'Region');
    var note  = document.createElement('span'); note.id = 'opmc-note';

    h2.parentNode.insertBefore(dests, h2);
    dests.parentNode.insertBefore(nav, dests.nextSibling);
    nav.appendChild(regs); nav.appendChild(note);

    var state = { dest: label(h2), region: null };
    var destBtns = {};   // name -> button, built once

    // Destination row is built ONCE. Switching only toggles a class — clearing
    // and rebuilding it (and moving the 60px heading between list items) made
    // the whole row collapse and re-flow for a frame, which read as a flicker.
    function buildDests() {
      destItems().forEach(function (item) {
        var name = label(item);
        if (!name || destBtns[name]) return;
        var li = document.createElement('li');
        var b = document.createElement('button');
        b.type = 'button';
        b.textContent = name;
        b.setAttribute('data-tag-item', 'home_destination_select');
        b.addEventListener('click', function () {
          if (state.dest === name) return;
          state.dest = name; state.region = null;
          paintDests();          // repaint immediately; no waiting, no jump
          // resolve live, for the same detached-node reason as the regions
          var live = destItems().filter(function (x) { return label(x) === name; })[0] || item;
          live.click();
          lastSig = null;            // force a re-read once the site has switched
          setTimeout(syncRegions, 400);
        });
        destBtns[name] = b;
        li.appendChild(b);
        dests.appendChild(li);
      });
    }

    function paintDests() {
      Object.keys(destBtns).forEach(function (name) {
        var b = destBtns[name], on = name === state.dest;
        b.classList.toggle('on', on);
        if (on) { b.setAttribute('aria-current', 'true'); b.setAttribute('role', 'heading'); b.setAttribute('aria-level', '2'); }
        else { b.removeAttribute('aria-current'); b.removeAttribute('role'); b.removeAttribute('aria-level'); }
      });
    }

    // Regions genuinely differ per destination, so this row is rebuilt — but it
    // is the small row, and it is rebuilt only after the site has switched.
    function renderRegions() {
      var rb = regionBtns();
      regs.innerHTML = ''; note.textContent = '';
      if (!rb.length) { note.textContent = 'All resorts in ' + state.dest + ' shown'; return; }
      if (!state.region) state.region = label(rb[0]);

      rb.forEach(function (src) {
        var name = label(src);
        // The site REPLACES these tab nodes after render, so a captured reference
        // goes detached and .click() on it silently does nothing. Resolve the
        // live node at click time instead — data-region-index is stable.
        var idx = src.getAttribute('data-region-index');
        var li = document.createElement('li'), b = document.createElement('button');
        b.type = 'button';
        b.textContent = name.replace(' (Big Island)', '');
        if (name === state.region) { b.className = 'on'; b.setAttribute('aria-current', 'true'); }
        var n = REGION_COUNTS[name];
        if (n) { var i = document.createElement('i'); i.textContent = n; b.appendChild(i); }
        b.setAttribute('data-tag-item', 'home_region_select');
        b.addEventListener('click', function () {
          if (state.region === name) return;
          state.region = name;
          // paint the selection now; the site filters the cards underneath
          [].slice.call(regs.querySelectorAll('button')).forEach(function (x) { x.classList.remove('on'); x.removeAttribute('aria-current'); });
          b.classList.add('on'); b.setAttribute('aria-current', 'true');
          var live = idx !== null
            ? document.querySelector('.destination-selection-tabs-lists button[data-region-index="' + idx + '"]')
            : null;
          if (!live) {
            live = regionBtns().filter(function (x) { return label(x) === name; })[0];
          }
          if (live) live.click();
        });
        li.appendChild(b); regs.appendChild(li);
      });
    }

    // The site renders its region tabs AFTER this builds on a cold load, and
    // build() early-returns once the nav exists — so a one-shot render left the
    // island chips empty until some unrelated re-render happened to rebuild us.
    // Track the site's tab set and re-render only when it actually changes
    // (a signature check, so observing the document can't loop us).
    var lastSig = null;
    function regionSig() {
      return regionBtns().map(label).join('|') + '@' + state.dest + '#' + (state.region || '');
    }
    function syncRegions() {
      var sig = regionSig();
      if (sig === lastSig) return;
      lastSig = sig;
      renderRegions();
    }

    function render() { buildDests(); paintDests(); syncRegions(); }

    render();
    var ctl = { render: render, sync: syncRegions, state: state };
    nav.__ctl = ctl;
    return ctl;
  }

  function apply() {
    var ctl = build();
    if (ctl && ctl.sync) ctl.sync();   // cheap: no-ops unless the site's tabs changed
  }

  apply();
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', apply);
  new MutationObserver(apply).observe(document.documentElement, { childList: true, subtree: true });
  window.__outriggerExplorerNav = apply;
})();
