#!/usr/bin/env bash
# features/home-page-v2/overlay.js is GENERATED — edit the sources, not the output.
#   prototypes/home-page-v2/variation.js   banner + tile CTAs + offers + sand theme
#   prototypes/explorer-nav/variation.js   destination / region navigation
# One preview URL (?opmc=home-page-v2) shows everything together. They are still
# separate A/B tests — see docs/next-tests.html for why 04 runs alone.
set -euo pipefail
cd "$(dirname "$0")/.."
out=features/home-page-v2/overlay.js
{
  echo "/* GENERATED by scripts/build-home-page-v2.sh — do not edit."
  echo "   Sources: prototypes/home-page-v2/variation.js + prototypes/explorer-nav/variation.js"
  echo "   Combined for ONE preview URL. They remain separate A/B tests. */"
  echo
  cat prototypes/home-page-v2/variation.js
  echo
  cat prototypes/explorer-nav/variation.js
} > "$out"
node --check "$out"
echo "built $out ($(wc -c < "$out") bytes)"
